<a href="https://colab.research.google.com/github/mwasalski/Data_Science_Bootcamp/blob/main/Intro_do_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [2]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

###Podstawy macierzy

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [11]:
## podstawowym obiektem biblioteki numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodność elementów.

In [12]:
# 1D array
x = np.array([1,3])
x

array([1, 3])

In [13]:
print(x)

[1 3]


In [14]:
type(x)

numpy.ndarray

In [16]:
x.ndim #wymiar tablicy

1

In [17]:
x.shape #kształt

(2,)

In [18]:
x.size #liczba elementów tablicy

2

In [20]:
x.dtype #typ tablicy

dtype('int64')

In [23]:
x = np.array([1.3, 2.3,5.6])

In [24]:
print(x)

[1.3 2.3 5.6]


In [25]:
x.dtype

dtype('float64')

In [6]:
#2D array
x = np.array([[1,2,3], [-1,4,2]])
x

array([[ 1,  2,  3],
       [-1,  4,  2]])

In [7]:
x.ndim

2

In [8]:
x.shape

(2, 3)

In [9]:
##bardzo ważne nauczyć się poprawnie operaować kształtami macierzy!!

In [10]:
x = np.array([[1,2,3],[9,8,8]])
print(x)

[[1 2 3]
 [9 8 8]]


In [11]:
# 3D array
# jeszcze bardziej zagnieżdżone macierze

In [14]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

     [[4,1,3],
      [4,5,6]]]

)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 5 6]]]


In [15]:
x.ndim

3

In [16]:
x.shape

(2, 2, 3)

###Typy danych

In [20]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [23]:
##nadawanie konkretnego typu danych
a = np.array([1,2,3], dtype = 'float')
a.dtype
print(a)

[1. 2. 3.]


In [24]:
a = np.array([1,2,3], dtype = 'complex')
a.dtype
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [25]:
##bardzo uważać - 2,9 przytnie jako 2
a = np.array([1.0,2.9,3.8], dtype = 'int')
a.dtype

dtype('int64')

In [27]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [28]:
##do opisywania obrazów najlepiej używac uint8, żeby to wszystko mniej ważyło
a = np.array([24,120,230], dtype = np.uint8)
a.dtype

dtype('uint8')

###Tworzenie tablic

In [31]:
np.zeros(shape = (4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape = (4,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.ones(shape = (5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.full(shape = (3,3), fill_value = 6, dtype = 'int')

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(start = 6, stop = 16)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.arange(start = 10, stop = 1000, step = 12)

array([ 10,  22,  34,  46,  58,  70,  82,  94, 106, 118, 130, 142, 154,
       166, 178, 190, 202, 214, 226, 238, 250, 262, 274, 286, 298, 310,
       322, 334, 346, 358, 370, 382, 394, 406, 418, 430, 442, 454, 466,
       478, 490, 502, 514, 526, 538, 550, 562, 574, 586, 598, 610, 622,
       634, 646, 658, 670, 682, 694, 706, 718, 730, 742, 754, 766, 778,
       790, 802, 814, 826, 838, 850, 862, 874, 886, 898, 910, 922, 934,
       946, 958, 970, 982, 994])

In [44]:
#od Z do A
np.arange(start = 1000, stop = 10, step = -10)

array([1000,  990,  980,  970,  960,  950,  940,  930,  920,  910,  900,
        890,  880,  870,  860,  850,  840,  830,  820,  810,  800,  790,
        780,  770,  760,  750,  740,  730,  720,  710,  700,  690,  680,
        670,  660,  650,  640,  630,  620,  610,  600,  590,  580,  570,
        560,  550,  540,  530,  520,  510,  500,  490,  480,  470,  460,
        450,  440,  430,  420,  410,  400,  390,  380,  370,  360,  350,
        340,  330,  320,  310,  300,  290,  280,  270,  260,  250,  240,
        230,  220,  210,  200,  190,  180,  170,  160,  150,  140,  130,
        120,  110,  100,   90,   80,   70,   60,   50,   40,   30,   20])

In [46]:
np.arange(start = 1.0, stop = 0.05, step = -0.08)

array([1.  , 0.92, 0.84, 0.76, 0.68, 0.6 , 0.52, 0.44, 0.36, 0.28, 0.2 ,
       0.12])

In [50]:
#parametr num = ile elementów z tego przedziału ma zostać wygenerowanych
np.linspace(start = 0, stop = 9, num = 100) 

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

In [51]:
#zmiana kształtu naszych danych
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
#tutaj python sam dopiero liczbę kolumn, jakie może być jeżeli chcemy mieć trzy wiersze
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
a.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###Podstawowe operacje na tablicach

In [59]:
a = np.array([1,2,3, 5])
b = np.array([5,7,8,9])

In [60]:
print(a)

[1 2 3 5]


In [61]:
print(b)

[5 7 8 9]


In [62]:
a + b

array([ 6,  9, 11, 14])

In [63]:
a - b

array([-4, -5, -5, -4])

In [64]:
a * b

array([ 5, 14, 24, 45])

In [65]:
a / b

array([0.2       , 0.28571429, 0.375     , 0.55555556])

In [66]:
a + 3 ##dodaje 3 do KAŻDEGO elementu

array([4, 5, 6, 8])

In [67]:
a + 3*b

array([16, 23, 27, 32])

In [68]:
np.add(a,b)

array([ 6,  9, 11, 14])

In [70]:
np.subtract(a,b)

array([-4, -5, -5, -4])

In [71]:
np.multiply(a,b)

array([ 5, 14, 24, 45])

In [72]:
np.divide(a,b)

array([0.2       , 0.28571429, 0.375     , 0.55555556])

In [73]:
##mnożenie macierzowe

In [80]:
x = np.array([[1,3], [2,0]])
y = np.array([[3,4], [5,6]])
print(x)

[[1 3]
 [2 0]]


In [81]:
x * y

array([[ 3, 12],
       [10,  0]])

In [83]:
np.dot(x,y) #prawidłowo pomnożona macierz

array([[18, 22],
       [ 6,  8]])

In [84]:
x.dot(y)

array([[18, 22],
       [ 6,  8]])

In [85]:
y.dot(x)

array([[11,  9],
       [17, 15]])

In [86]:
x @ y

array([[18, 22],
       [ 6,  8]])

###Generowanie liczba pseudolosowych

In [87]:
np.random.seed(0)

In [88]:
np.random.randn(

)

1.764052345967664

In [89]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [90]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [91]:
#rozkład jednostajny na przedziale
np.random.rand()

0.1965823616800535

In [92]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [93]:
np.random.rand(10,4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [95]:
np.random.randint(10) #zwraca losową wartość <10

0

In [97]:
np.random.randint(low = 10, high = 99)

34

In [98]:
np.random.randint(low = 10, high = 99, size = 10)

array([39, 31, 35, 90, 70, 71, 93, 43, 42, 80])

In [100]:
np.random.choice([4,2,1,5]) #losowy obiekt z listy

5

In [102]:
np.random.choice(['python','java','sql','r']) #losowy obiekt z listy

'r'

In [104]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.random.shuffle(data) #tasowanie liczb

In [106]:
data #tutaj dostaniemy od razu zmianę, w pandasie trzeba dodatkowo przypisać tę zmianę do zmiennej

array([4, 6, 3, 5, 0, 2, 1, 7, 9, 8])

###Podstawowe funkcje

In [109]:
np.exp(1) #exponent

2.718281828459045

In [110]:
np.exp(9)

8103.083927575384

In [112]:
np.sqrt(4) #pierwiastek kwadratowy

2.0

In [114]:
np.all([2,3,4,5]) #jeśli choćby jedna wartość zwróci False (np. jak damy 0) to cała funkcja da False

True

In [116]:
np.any([1,2,0]) #sprawdza, czy jakikolwiek obiekt jest True

True

In [118]:
a = np.random.rand(5)
a

array([0.35404666, 0.55181626, 0.03362509, 0.96896177, 0.32099724])

In [120]:
np.argmax(a) #zwraca numer indeksu z największą wartością

3

In [121]:
np.argmin(a) #zwraca numer indeksu z najmniejszą wartością

2

In [125]:
np.argsort(a) #sortowane a-z, użyteczne przy wielu klasach, gdzie chcemy sprawdzić pierwsze dwie, trzy itp

array([2, 4, 0, 1, 3])

In [126]:
np.max(a)

0.9689617652602737

In [127]:
np.mean(a)

0.44588940426993445

In [128]:
np.median(a)

0.3540466620838102

In [129]:
np.std(a)

0.30945765364392996

###Indeksowanie i wycinanie

In [131]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [132]:
# a[idx], a[start:stop], a[:stop]

In [133]:
a[2]

2

In [135]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [136]:
a[[0, 10]]

array([ 0, 10])

In [137]:
a[-1]

19

In [148]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
 a[1] #wyciannie wiersza

array([5, 6, 7, 8, 9])

In [145]:
a[:, 3] #wyciannie kolumny

array([ 3,  8, 13, 18])

In [146]:
a[1,3]

8

In [150]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [152]:
a[1,2] = 14 #przypisawanie nowych wartości do tablicy
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###Iteracja po tablicach

In [153]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
for row in a:
  print(a)

[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [155]:
for row in a:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [156]:
for row in a:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [157]:
for item in a.flat: #wypłaszcza tablice
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


###Zmiana rozmiaru tablic

In [158]:
a.shape

(4, 5)

In [160]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [163]:
a.ravel() #wypłaszczanie danych - 1D

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [165]:
a.T #transpozycja

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

###Maski logiczne

In [170]:
a = np.arange(start = -10, stop = 10, step = 0.5)
a = a.reshape(10,-1)

In [171]:
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [173]:
a > 0 #maska logiczna

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [176]:
a[a>0] #tutaj dostaniemy tylko TRUE

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [179]:
np.bitwise_and(a>-5, a<5) #zakres

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [181]:
a[np.bitwise_and(a>-5, a<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [182]:
np.bitwise_or(a<-5, a>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

###Algebra liniowa

In [6]:
#norma wektorowa

v1 = np.array([-1,4])
v1

array([-1,  4])

In [11]:
# norma euklidesowa

np.linalg.norm(v1)

4.123105625617661

In [15]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [16]:
#odległość dwóch punktów w przestrzeni R2

In [17]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [18]:
#odległość dwóch punktów w przestrzeni Rn

In [20]:
p = np.array([3,0, 1])
q = np.array([0,4, 2])

np.linalg.norm(p-q)

5.0990195135927845

In [21]:
# mnożenie macierzy

In [24]:
 x = np.array([[5,3], [3,9]])
y = np.array([[1],[-1]])
print(x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [27]:
z = np.dot(x, y)
print(z)

[[ 2]
 [-6]]


In [28]:
z.shape

(2, 1)