<a href="https://colab.research.google.com/github/mwasalski/Data_Science_Bootcamp/blob/main/Intro_do_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [3]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [11]:
## podstawowym obiektem biblioteki numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodność elementów.

In [12]:
# 1D array
x = np.array([1,3])
x

array([1, 3])

In [13]:
print(x)

[1 3]


In [14]:
type(x)

numpy.ndarray

In [16]:
x.ndim #wymiar tablicy

1

In [17]:
x.shape #kształt

(2,)

In [18]:
x.size #liczba elementów tablicy

2

In [20]:
x.dtype #typ tablicy

dtype('int64')

In [23]:
x = np.array([1.3, 2.3,5.6])

In [24]:
print(x)

[1.3 2.3 5.6]


In [25]:
x.dtype

dtype('float64')

In [6]:
#2D array
x = np.array([[1,2,3], [-1,4,2]])
x

array([[ 1,  2,  3],
       [-1,  4,  2]])

In [7]:
x.ndim

2

In [8]:
x.shape

(2, 3)

In [9]:
##bardzo ważne nauczyć się poprawnie operaować kształtami macierzy!!

In [10]:
x = np.array([[1,2,3],[9,8,8]])
print(x)

[[1 2 3]
 [9 8 8]]


In [11]:
# 3D array
# jeszcze bardziej zagnieżdżone macierze

In [14]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

     [[4,1,3],
      [4,5,6]]]

)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 5 6]]]


In [15]:
x.ndim

3

In [16]:
x.shape

(2, 2, 3)