<a href="https://colab.research.google.com/github/mwasalski/Data_Science_Bootcamp/blob/main/ML_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Machine Learning course

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Preprocesing

In [ ]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.3.2'

In [ ]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw


size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [ ]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


## Kategoryzacja danych - warto to robić, aby w później fazie, przy tworzeniu wykresów, jest bardziej elegancko i jest to po prostu efektywniejsze

In [ ]:
for col in ['size','color','gender','bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes


In [ ]:
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [ ]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [ ]:
df.describe(include='category').T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

## Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() #tworzymy instancję i przypisujemy do zmiennej le
#stosować raczej do zmiennych binarnych, do zmiennych kategorycznych są inne rzeczy
le.fit(df['bought']) #dopasuje encoder do naszej zmiennej
le.transform(df['bought'])

array([1, 0, 1, 0, 1], dtype=int64)

In [ ]:
le.fit_transform(df['bought']) #wszystko w jednym

array([1, 0, 1, 0, 1])

In [ ]:
le.classes_ #zaczynamy od 0, gdyby było więcej klas to byłoby powyżej 2,3,4 itp

array(['no', 'yes'], dtype=object)

In [ ]:
df['bought'] = le.fit_transform(df['bought'])

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [ ]:
df['bought'] = le.inverse_transform(df['bought']) #powrót do pierwotnej wersji

## OneHot Encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder #klasa OneHotEncoder z modułu preprocessing

encoder = OneHotEncoder(sparse_output=False) #
encoder.fit(df[['size']]) #

OneHotEncoder(sparse_output=False)

In [ ]:
encoder.transform(df[['size']]) #podwójny nawias kwadratowy daje macierz 2D - numpy array

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [ ]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

### Jak to czytać ?
gdybyśmy nałożyli na siebie transform i categories_ to by wyszło, że L jest w drugim i czwartym wierszu pierwszej kolumny. M w trzecim i piątym drugiej kolumny i XL w pierwszym trzeciej kolumny


In [ ]:
df['size'] #używanie jednego nawiasu kwadratowego daje Series

0    XL
1     L
2     M
3     L
4     M
Name: size, dtype: category
Categories (3, object): ['L', 'M', 'XL']

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

## pd.get_dummies()

In [ ]:
pd.get_dummies(data=df, dtype=int) #bez dtype dostaniemy True/False

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0     500       0       0        1           0            0          1   
1   89.0     450       1       0        0           0            1          0   
2   99.0     300       0       1        0           1            0          0   
3  129.0     380       1       0        0           0            1          0   
4   79.0     410       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

In [ ]:
pd.get_dummies(data=df, dtype=int, drop_first=True) #wyrzuca pierwsza kolumnę DLA DANEJ KATEGORII np. size_L, color_blue, bought_no

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0     500       0        1            0          1            0   
1   89.0     450       0        0            1          0            1   
2   99.0     300       1        0            0          0            1   
3  129.0     380       0        0            1          0            0   
4   79.0     410       1        0            0          1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [ ]:
pd.get_dummies(data=df, dtype=int, drop_first=True, prefix = 'new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0     500      0       1          0        1         0        1
1   89.0     450      0       0          1        0         1        0
2   99.0     300      1       0          0        0         1        1
3  129.0     380      0       0          1        0         0        0
4   79.0     410      1       0          0        1         0        1

In [ ]:
pd.get_dummies(data=df, dtype=int, drop_first=True, prefix_sep = '-')

price  weight  size-M  size-XL  color-green  color-red  gender-male  \
0  199.0     500       0        1            0          1            0   
1   89.0     450       0        0            1          0            1   
2   99.0     300       1        0            0          0            1   
3  129.0     380       0        0            1          0            0   
4   79.0     410       1        0            0          1            0   

   bought-yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [ ]:
pd.get_dummies(data=df, dtype=int, drop_first=True, columns=['size'])

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0     500    yes       0        1
1  green    male   89.0     450     no       0        0
2   blue    male   99.0     300    yes       1        0
3  green  female  129.0     380     no       0        0
4    red  female   79.0     410    yes       1        0

## Standaryzacja

In [ ]:
#StandardScaler

#std() - pandas nieobciązony estymator wariancji, numpy obciążony
#

In [ ]:
# własna funkcja standaryzacji

def standardize(x):
    return (x-x.mean()) / x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [ ]:
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [ ]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [ ]:

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [ ]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [ ]:
le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()

df[['price','weight']] = scaler.fit_transform(df[['price','weight']])

df = pd.get_dummies(data=df, drop_first=True, dtype=int)

df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0